### ISSUE TITLE
Crash in AtlasSimInterface from sending walk messages too quickly.

### ISSUE THREAD

**Issue by osrf-migration** [osrf/drcsim#230]
**Original report ([archived issue](https://osrf-migration.github.io/drcsim-gh-pages/#!/osrf/drcsim/issues/230)) by andy_somerville (Bitbucket: [andy_somerville](https://bitbucket.org/%7B09fd5d4b-d90e-4416-9a6a-2e5cd638472c%7D/)).**

----------------------------------------
Not sure if there is a separate bug reporting mechanism for libAtlasSimInterface.so, but I'm adding it here for lack of a better option.

Crash is apparently because I errantly sent 4 walk messages in quick succession. 

Upon sending a walk command to /atlas/atlas_sim_interface_command Gazebo exits with no error message. Crash is repeatable.

```
#!terminal

[gazebo-2] process has finished cleanly
log file: <redacted>/.ros/log/d94c4eee-b1e3-11e2-8761-0025648c7b5e/gazebo-2*.log
```

Using gdb with --pid attaching to gzserver and catching syscall 60 and breaking at _exit I was able to observe a segfault at the moment of the crash.

```
#!gdb

#0  0x00007fc48197083c in ?? () from /usr/lib/drcsim-2.5/AtlasSimInterface_1.0.8/libAtlasSimInterface.so
#1  0x00007fc481988613 in ?? () from /usr/lib/drcsim-2.5/AtlasSimInterface_1.0.8/libAtlasSimInterface.so
#2  0x00007fc481988695 in ?? () from /usr/lib/drcsim-2.5/AtlasSimInterface_1.0.8/libAtlasSimInterface.so
#3  0x00007fc481962a6c in ?? () from /usr/lib/drcsim-2.5/AtlasSimInterface_1.0.8/libAtlasSimInterface.so
#4  0x00007fc481c8fc53 in ?? () from /usr/lib/drcsim-2.5/AtlasSimInterface_1.0.8/libAtlasSimInterface.so
#5  0x00007fc481923096 in ?? () from /usr/lib/drcsim-2.5/AtlasSimInterface_1.0.8/libAtlasSimInterface.so
#6  0x00007fc48189956f in ?? () from /usr/lib/drcsim-2.5/AtlasSimInterface_1.0.8/libAtlasSimInterface.so
#7  0x00007fc4818978fd in ?? () from /usr/lib/drcsim-2.5/AtlasSimInterface_1.0.8/libAtlasSimInterface.so
#8  0x00007fc48189a709 in ?? () from /usr/lib/drcsim-2.5/AtlasSimInterface_1.0.8/libAtlasSimInterface.so
#9  0x00007fc481895a50 in ?? () from /usr/lib/drcsim-2.5/AtlasSimInterface_1.0.8/libAtlasSimInterface.so
#10 0x00007fc48236e00b in gazebo::AtlasPlugin::UpdateStates() () from /usr/lib/drcsim-2.5/plugins/libAtlasPlugin.so
#11 0x00007fc52610d2ee in gazebo::physics::World::Update() () from /usr/lib/libgazebo_physics.so.1
#12 0x00007fc5261150a8 in gazebo::physics::World::Step() () from /usr/lib/libgazebo_physics.so.1
#13 0x00007fc526117a54 in gazebo::physics::World::RunLoop() () from /usr/lib/libgazebo_physics.so.1
#14 0x00007fc524cface9 in thread_proxy () from /usr/lib/libboost_thread.so.1.46.1
#15 0x00007fc525862e9a in start_thread (arg=0x7fc47bfff700) at pthread_create.c:308
#16 0x00007fc5240a3ccd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:112
#17 0x0000000000000000 in ?? ()

```

Immediately after being sent 4 messages in rapid succession that looked like this except that the step_index for respective messages would have started at 0 and be sent in groups of 4:

```
#!json

header: 
  seq: 3
  stamp: 
    secs: 0
    nsecs: 0
  frame_id: ''
behavior: 4
walk_params: 
  step_data: 
    - 
      step_index: 12
      foot_index: 0
      duration: 0.63
      pose: 
        position: 
          x: 2.56717912253
          y: 0.141389053762
          z: 8.75890254974e-05
        orientation: 
          x: 0.00124522134858
          y: -0.00326941626078
          z: -0.0147462411844
          w: 0.999885147761
      swing_height: 0.05
    - 
      step_index: 13
      foot_index: 1
      duration: 0.63
      pose: 
        position: 
          x: 2.78717912253
          y: -0.148610946238
          z: 8.75890254974e-05
        orientation: 
          x: 0.00124522134858
          y: -0.00326941626078
          z: -0.0147462411844
          w: 0.999885147761
      swing_height: 0.05
    - 
      step_index: 14
      foot_index: 0
      duration: 0.63
      pose: 
        position: 
          x: 3.00717912253
          y: 0.141389053762
          z: 8.75890254974e-05
        orientation: 
          x: 0.00124522134858
          y: -0.00326941626078
          z: -0.0147462411844
          w: 0.999885147761
      swing_height: 0.05
    - 
      step_index: 15
      foot_index: 1
      duration: 0.63
      pose: 
        position: 
          x: 3.00217912253
          y: -0.148610946238
          z: 8.75890254974e-05
        orientation: 
          x: 0.00124522134858
          y: -0.00326941626078
          z: -0.0147462411844
          w: 0.999885147761
      swing_height: 0.05
  use_demo_walk: False
step_params: 
  desired_step: 
    step_index: 0
    foot_index: 0
    duration: 0.0
    pose: 
      position: 
        x: 0.0
        y: 0.0
        z: 0.0
      orientation: 
        x: 0.0
        y: 0.0
        z: 0.0
        w: 0.0
    swing_height: 0.0
  use_demo_walk: False
stand_params: 
  use_desired_pelvis_height: False
  desired_pelvis_height: 0.0
  desired_pelvis_yaw: 0.0
  desired_pelvis_lat: 0.0
manipulate_params: 
  use_desired: False
  desired: 
    pelvis_height: 0.0
    pelvis_yaw: 0.0
    pelvis_lat: 0.0
  use_demo_mode: False
k_effort: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
---
```

Versions:
gazebo: 1.7.1-1~precise
drcsim: 2.5.2-1~precise

I have a core, but it's 3.8GB...
