### ISSUE TITLE
BDI modes change the hand force/torque sensor behavior

### ISSUE THREAD

**Issue by osrf-migration** [osrf/drcsim#273]
**Original report ([archived issue](https://osrf-migration.github.io/drcsim-gh-pages/#!/osrf/drcsim/issues/273)) by Alberto Romay (Bitbucket: [romayiii](https://bitbucket.org/%7Bfb492998-8910-4cd2-b48f-87008207356c%7D/)).**

----------------------------------------
The hand force/torque sensor behaves well until the BDI modes are changed. While in STAND mode the output of the sensor is correct, however, when the mode is changed to MANIPULATE for example, the force/torque sensor start giving a nonsense output.

[Hand force sensor while changing BDI modes](http://www.youtube.com/watch?v=z9TETDM4PMU)

**Comment by osrf-migration** [comment]
**Original comment by John Hsu (Bitbucket: [hsu](https://bitbucket.org/%7B0a186eae-abf0-4514-a951-23db5eccc286%7D/), GitHub: [hsu](https://github.com/hsu)).**

----------------------------------------
In "Manipulate" mode, the upper body is controlled by PID joint servo.  Can you check to see what gains are active?  I.e. please post a frame of ROS topic `/atlas/atlas_state` containing [atlas_msgs::AtlasState messages](https://github.com/osrf/drcsim/blob/e4a9d846a87fa7ec41ab7408e635b335c0898bcb/ros/atlas_msgs/msg/AtlasState.msg#L47) by running: 

~~~
rostopic echo /atlas/atlas_state
~~~

Thanks.

**Comment by osrf-migration** [comment]
**Original comment by John Hsu (Bitbucket: [hsu](https://bitbucket.org/%7B0a186eae-abf0-4514-a951-23db5eccc286%7D/), GitHub: [hsu](https://github.com/hsu)).**

----------------------------------------

* changed state from "new" to "invalid"

Please reopen if reducing controller gains do not help.

**Comment by osrf-migration** [comment]
**Original comment by DavidC (Bitbucket: [DavidC](https://bitbucket.org/%7Bfcd58e93-ca10-45f7-b2db-c913c5878cc3%7D/)).**

----------------------------------------
Duplicated issue with below gains.

This does not occur if I add the kp_velocity = [50.0]*num joints used in mode change tutorial.

```
#!c++
---
header: 
  seq: 158616
  stamp: 
    secs: 158
    nsecs: 617000000
  frame_id: ''
position: [-0.004253497812896967, 0.003138535190373659, 0.0005494514480233192, -0.0545525997877121, 0.0005017297226004303, 0.07777851074934006, -0.35947710275650024, 0.6584494113922119, -0.29676908254623413, -0.08471138775348663, -0.0008100775885395706, -0.08756644278764725, -0.30173590779304504, 0.644160270690918, -0.34017395973205566, 0.08133593201637268, -0.00010546205885475501, -0.057346656918525696, 0.00043056384311057627, -1.4408309652935714e-05, -0.0017577768303453922, -0.0610082782804966, 0.00019322791195008904, 0.05726254731416702, 0.00047053940943442285, 1.531421185063664e-05, -0.001912393607199192, 0.060994721949100494]
velocity: [0.18495392799377441, -0.049183301627635956, 0.0033359096851199865, 0.009949360974133015, -0.0004996269708499312, -0.006853158585727215, -0.024184074252843857, 0.000641675025690347, -0.004282943904399872, -0.005835562478750944, -0.004844920709729195, -0.006593417841941118, -0.031358979642391205, 0.015458776615560055, -0.01360311545431614, -0.005812288727611303, -0.3416707217693329, -0.008576014079153538, 7.490523338317871, 0.0015963533660396934, -7.671793460845947, 0.0035639707930386066, 0.3295316994190216, -0.014395559206604958, 0.8433672189712524, -0.0009480057051405311, -0.8909074068069458, 0.011512752622365952]
effort: [1.0353909730911255, -13.08605670928955, -1.054603099822998, 1.104151725769043, 2.7403652667999268, 29.980243682861328, -17.309946060180664, -42.87071228027344, 14.923989295959473, 0.6861569881439209, -1.9611177444458008, -29.50182342529297, -13.263740539550781, -37.365108489990234, 21.935344696044922, 0.2541794776916504, -71.70421600341797, 56.267059326171875, 114.0, 0.03435596078634262, -10.502946853637695, 6.006003379821777, 67.6646957397461, -58.79983901977539, 11.593825340270996, -0.02352869138121605, -0.6230703592300415, -6.0010905265808105]
kp_position: [20.0, 4000.0, 2000.0, 20.0, 5.0, 100.0, 2000.0, 1000.0, 900.0, 300.0, 5.0, 100.0, 2000.0, 1000.0, 900.0, 300.0, 2000.0, 1000.0, 200.0, 200.0, 50.0, 100.0, 2000.0, 1000.0, 200.0, 200.0, 50.0, 100.0]
ki_position: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
kd_position: [5.0, 5.0, 5.0, 1.0, 0.009999999776482582, 1.0, 10.0, 10.0, 2.0, 1.0, 0.009999999776482582, 1.0, 10.0, 10.0, 2.0, 1.0, 200.0, 100.0, 20.0, 20.0, 1.0, 10.0, 200.0, 100.0, 20.0, 20.0, 1.0, 10.0]
kp_velocity: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
i_effort_min: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
i_effort_max: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
k_effort: [255, 255, 255, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255]
orientation: 
  x: 0.00334710437225
  y: -0.00101400226396
  z: 0.0385224665403
  w: 0.999251614091
angular_velocity: 
  x: -0.00322587483531
  y: -0.0296533028646
  z: -0.00635233595385
linear_acceleration: 
  x: -0.297771675951
  y: 0.0678834885125
  z: 9.62144519575
l_foot: 
  force: 
    x: 0.0
    y: 0.0
    z: 458.626688345
  torque: 
    x: -0.691853246167
    y: -14.688912482
    z: 0.0
r_foot: 
  force: 
    x: 0.0
    y: 0.0
    z: 475.68321606
  torque: 
    x: -0.260185463723
    y: -21.8995147901
    z: 0.0
l_hand: 
  force: 
    x: -147.716859851
    y: 2.89881917031
    z: -65.8441972659
  torque: 
    x: -5.99412460166
    y: 1.17707030778
    z: 23.0405171858
r_hand: 
  force: 
    x: 127.310528748
    y: -12.4366944098
    z: -55.8304872829
  torque: 
    x: 6.01106469907
    y: 0.912495717281
    z: 17.7333580297
---


```
